### ISSUE TITLE
OSX install: env: node\r: No such file or directory

### ISSUE THREAD

**Issue by leonistor** [pumlhorse/pumlhorse#49]
Using Mac OSX 10.12.6, node v8.4.0, installed with
`npm install -g pumlhorse`
When trying to run `pumlhorse` it I get
`env: node\r: No such file or directory`

The problem comes from the line endings encoding in `bin/cli.js`, as they are CRLF.
Workaround: installed as local project dependency, changed "End of Line Sequence" from CRLF to LF in `./node_modules/.bin/pumlhorse`, used the local version:
`./node_modules/.bin/pumlhorse myfile.puml`

Suggestion: take a look at [the github docs for line endings](https://help.github.com/articles/dealing-with-line-endings/).

pumlhorse 🏇 is a sure bet, keep up the good work 😉 
Thank you!

**Comment by mdickin** [comment]
Thank you for the feedback, I will fix this as soon as I can! This is one of the downsides of using Windows for everything.

If you don't mind, I am interested in hearing how you're using Pumlhorse and any feedback you may have!

**Comment by leonistor** [comment]
I'm looking for a simple to use and effective tool for APIs acceptance testing. Haven't looked yet at pumlhorse-browser, but will do soon, for testing web interfaces and chatbots.

**Comment by mdickin** [comment]
This should be resolved in the new version. Man, so many tools want to "correct" line endings, it makes it hard to verify the change!
